apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: hashcash.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: authentication-srv
                port:
                  number: 3000
          - path: /api/kms/?(.*)
            pathType: Prefix
            backend:
              service:
                name: kms-srv
                port:
                  number: 3000
          - path: /api/tokenization/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tokenization-srv
                port:
                  number: 3000
          - path: /api/manage-business/?(.*)
            pathType: Prefix
            backend:
              service:
                name: manage-business-srv
                port:
                  number: 3000
          - path: /api/apikey/?(.*)
            pathType: Prefix
            backend:
              service:
                name: apikey-manager-srv
                port:
                  number: 3000
          - path: /api/checkout/?(.*)
            pathType: Prefix
            backend:
              service:
                name: checkout-srv
                port:
                  number: 3000
          - path: /api/customer/?(.*)
            pathType: Prefix
            backend:
              service:
                name: customer-srv
                port:
                  number: 3000
          - path: /api/payment/?(.*)
            pathType: Prefix
            backend:
              service:
                name: payment-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 4200
