apiVersion: apps/v1
kind: Deployment
metadata:
  name: apikey-manager-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apikey-manager
  template:
    metadata:
      labels:
        app: apikey-manager
    spec:
      containers:
        - name: apikey-manager
          image: jerry377/apikey-manager
          env:
            - name: MONGO_URI
              value: 'mongodb://apikey-manager-mongo-srv:27017/apikey-manager'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: hashCash
---
## note that we did not say the type of the service because the default is clusterIp and that's what we want
## to remember that the clusterIP service is only responsible for communication between pods inside the cluster it does not
## allow you to communicate with the outer world you could use load balancer for this or node port
apiVersion: v1
kind: Service
metadata:
  name: apikey-manager-srv
spec:
  selector:
    app: apikey-manager
  ports:
    - name: apikey-manager
      protocol: TCP
      port: 3000
      targetPort: 3000

