apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: jerry377/customer
          env:
            - name: MONGO_URI
              value: 'mongodb://customer-mongo-srv:27017/customer'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: hashCash
---
## note that we did not say the type of the service because the default is clusterIp and that's what we want
## to remember that the clusterIP service is only responsible for communication between pods inside the cluster it does not
## allow you to communicate with the outer world you could use load balancer for this or node port
apiVersion: v1
kind: Service
metadata:
  name: customer-srv
spec:
  selector:
    app: customer
  ports:
    - name: customer
      protocol: TCP
      port: 3000
      targetPort: 3000

