apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailing-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailing
  template:
    metadata:
      labels:
        app: emailing
    spec:
      containers:
        - name: emailing
          image: jerry377/emailing
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/asfuth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: EMAIL_USERNAME
              value: '9df67e3c386b8a'
            - name: EMAIL_HOST
              value: 'smtp.mailtrap.io'
            - name: EMAIL_PORT
              value: '587'
            - name: EMAIL_FROM
              value: 'mohamedpop.9559@gmail.com'
            - name: GMAIL_EMAIL
              value: 'hashcash.mail@gmail.com'
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailtrappassword
                  key: EMAIL_PASSWORD
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gmailpassword
                  key: GMAIL_PASSWORD
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: hashCash