name: deploy-tokenization

on:
  push:
    branches:
      - master
    paths:
      - 'tokenization/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tokenization && docker build -t jerry377/tokenization -f docker/Dockerfile-prod .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push jerry377/tokenization
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save hashcash2
      - run: kubectl rollout restart deployment tokenization-depl
