name: deploy-emailing

on:
  push:
    branches:
      - master
    paths:
      - 'emailing/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd emailing && docker build -t jerry377/emailing -f docker/Dockerfile-dev .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push jerry377/emailing
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-22-8-do-1-ams3-1655241509862
      - run: kubectl rollout restart deployment emailing-depl
